const brand=document.querySelector('#brand'),form=document.querySelector('#search-form'),input=document.querySelector('#search'),scopeAuthored=document.querySelector('#scope-authored'),scopeAssigned=document.querySelector('#scope-assigned'),scopeReview=document.querySelector('#scope-review'),showBots=document.querySelector('#show-bots'),graphOptions=document.querySelector('.graph-options'),refresh=document.querySelector('#refresh'),auto=document.querySelector('#auto'),updated=document.querySelector('#updated'),warnings=document.querySelector('#warnings'),errorBox=document.querySelector('#error'),lanes=document.querySelector('#lanes'),edges=document.querySelector('#edges'),empty=document.querySelector('#empty'),viewport=document.querySelector('#viewport'),progress=document.querySelector('#progress');
let timer=null,loading=false,lastUpdated=0,refreshFailures=0,retryAt=0,data=null,sourceData=null,renderFrame=null,pendingViewportState=null,initialLoadComplete=false,loadProgressValue=0;
const params=new URLSearchParams(location.search);input.value=params.get('q')||'';scopeAuthored.checked=!params.has('authored')||params.get('authored')==='1';scopeAssigned.checked=!params.has('assigned')||params.get('assigned')==='1';scopeReview.checked=!params.has('reviewRequested')||params.get('reviewRequested')==='1';

function escapeHTML(value){const node=document.createElement('span');node.textContent=value??'';return node.innerHTML}
function status(label,kind=''){return `<span class="status ${kind}">${label}</span>`}
function relationLabel(r){return r==='mine'?'My merge request':r==='assigned'?'Assigned':r==='review-requested'?'Review requested':'Other'}
function prStateIcon(isDraft){const path=isDraft?'M3.25 1A2.25 2.25 0 0 1 4 5.372v5.256a2.251 2.251 0 1 1-1.5 0V5.372A2.251 2.251 0 0 1 3.25 1Zm9.5 14a2.25 2.25 0 1 1 0-4.5 2.25 2.25 0 0 1 0 4.5ZM2.5 3.25a.75.75 0 1 0 1.5 0 .75.75 0 0 0-1.5 0ZM3.25 12a.75.75 0 1 0 0 1.5.75.75 0 0 0 0-1.5Zm9.5 0a.75.75 0 0 0 0-1.5.75.75 0 0 0 0 1.5ZM14 7.5a1.25 1.25 0 1 1-2.5 0 1.25 1.25 0 0 1 2.5 0Zm0-4.25a1.25 1.25 0 1 1-2.5 0 1.25 1.25 0 0 1 0 2.5Z':'M1.5 3.25a2.25 2.25 0 1 1 3 2.122v5.256a2.251 2.251 0 1 1-1.5 0V5.372A2.25 2.25 0 0 1 1.5 3.25Zm5.677-.177L9.573.677A.25.25 0 0 1 10 .854V2.5h1A2.5 2.5 0 0 1 13.5 5v5.628a2.251 2.251 0 1 1-1.5 0V5a1 1 0 0 0-1-1h-1v1.646a.25.25 0 0 1-.427.177L7.177 3.427a.25.25 0 0 1 0-.354ZM3.75 2.5a.75.75 0 1 0 0 1.5.75.75 0 0 0 0-1.5Zm0 9.5a.75.75 0 1 0 0 1.5.75.75 0 0 0 0-1.5Zm8.25.75a.75.75 0 0 0 1.5 0 .75.75 0 0 0-1.5 0Z';const label=isDraft?'Draft merge request':'Open merge request';return `<span class="pr-state-icon ${isDraft?'draft-icon':'ready-icon'}" title="${label}" role="img" aria-label="${label}"><svg viewBox="0 0 16 16" aria-hidden="true"><path d="${path}"></path></svg></span>`}
function nodeHTML(node){
 if(node.kind==='repository'){const r=node.repository,name=escapeHTML(r.nameWithOwner);return `<article class="node repo" data-id="${escapeHTML(node.id)}"><strong>${r.url?`<a class="repo-link" href="${escapeHTML(r.url)}" target="_blank" rel="noreferrer">${name}</a>`:name}</strong></article>`}
 if(node.kind==='branch'){const b=node.branch,name=escapeHTML(b.name);return `<article class="node branch" data-id="${escapeHTML(node.id)}" aria-label="Base branch ${name}"><strong>${b.url?`<a class="repo-link" href="${escapeHTML(b.url)}" target="_blank" rel="noreferrer">${name}</a>`:name}</strong></article>`}
 const p=node.pullRequest,approval=approvalStatus(p),ciKind=p.ciState==='SUCCESS'?'ok':p.ciState==='FAILURE'||p.ciState==='ERROR'?'bad':'warn',conflict=p.mergeable==='CONFLICTING'?status('⚠ Conflict','bad'):'';
 const assigneeLabel=p.assignees?.length===1?'Assignee':'Assignees',assignees=p.assignees?.length?`<div class="assignees">${assigneeLabel}: ${p.assignees.map(x=>'@'+escapeHTML(x.login)).join(', ')}</div>`:'';
 return `<article class="node ${p.isDraft?'draft':'ready'} ${p.relation}" data-id="${escapeHTML(node.id)}" aria-label="${relationLabel(p.relation)}${p.isDraft?', Draft':', Ready for review'}"><div class="title-row">${prStateIcon(p.isDraft)}<a class="title" href="${escapeHTML(p.url)}" target="_blank" rel="noreferrer">!${p.number} ${escapeHTML(p.title)}</a></div><div class="author">${p.author.avatarUrl?`<img class="avatar" src="${escapeHTML(p.author.avatarUrl)}" alt="">`:''}<span>@${escapeHTML(p.author.login)}</span></div>${assignees}<div class="statuses">${status(approval.label,approval.kind)}${status(`● Pipeline ${p.ciState||'UNKNOWN'}`,ciKind)}${conflict}</div></article>`
}
function nodeRepositoryID(node){return node.kind==='pullRequest'?node.pullRequest.repositoryId:node.kind==='branch'?node.branch.repositoryId:node.repository?.id}
function layoutLane(lane,repoNode,prs,result){
 const nodeWidth=290,horizontalGap=72,verticalGap=24,byID=new Map(prs.map(node=>[node.id,node])),ids=new Set(byID.keys()),children=new Map(),hasParent=new Set();for(const node of prs)children.set(node.id,[]);
 for(const edge of result.edges){if(!ids.has(edge.source)||!ids.has(edge.target)||hasParent.has(edge.target))continue;children.get(edge.source).push(edge.target);hasParent.add(edge.target)}
 const roots=prs.filter(node=>!hasParent.has(node.id)),subtreeHeight=new Map(),visiting=new Set(),element=id=>lane.querySelector(`[data-id="${CSS.escape(id)}"]`);
 function measure(id){if(subtreeHeight.has(id))return subtreeHeight.get(id);const el=element(id),own=el?.offsetHeight||1;if(visiting.has(id))return own;visiting.add(id);const kids=children.get(id)||[],desc=kids.map(measure).reduce((sum,height)=>sum+height,0)+Math.max(0,kids.length-1)*verticalGap,height=Math.max(own,desc);visiting.delete(id);subtreeHeight.set(id,height);return height}
 const positions=new Map();function place(id,top){const el=element(id),own=el?.offsetHeight||1,height=measure(id),kids=children.get(id)||[];positions.set(id,top+(height-own)/2);let childTop=kids.length===1?top+(height-measure(kids[0]))/2:top;for(const child of kids){place(child,childTop);childTop+=measure(child)+verticalGap}}
 let top=0;for(const root of roots){place(root.id,top);top+=measure(root.id)+verticalGap}const contentHeight=Math.max(1,top-verticalGap),repoEl=element(repoNode.id),repoHeight=repoEl?.offsetHeight||1,laneHeight=Math.max(contentHeight,repoHeight);if(repoEl){repoEl.style.left='0px';repoEl.style.top=`${(laneHeight-repoHeight)/2}px`}
 let maxRank=0;for(const node of prs){maxRank=Math.max(maxRank,node.rank);const el=element(node.id);if(el){el.style.left=`${node.rank*(nodeWidth+horizontalGap)}px`;el.style.top=`${positions.get(node.id)??0}px`}}lane.style.width=`${(maxRank+1)*nodeWidth+maxRank*horizontalGap}px`;lane.style.height=`${laneHeight}px`
}
function captureViewport(){const bounds=viewport.getBoundingClientRect(),centerX=bounds.left+bounds.width/2,centerY=bounds.top+bounds.height/2;let anchor=null,distance=Infinity;for(const node of lanes.querySelectorAll('.node[data-id]')){const rect=node.getBoundingClientRect();if(rect.right<bounds.left||rect.left>bounds.right||rect.bottom<bounds.top||rect.top>bounds.bottom)continue;const value=(rect.left+rect.width/2-centerX)**2+(rect.top+rect.height/2-centerY)**2;if(value<distance){distance=value;anchor={id:node.dataset.id,left:rect.left-bounds.left,top:rect.top-bounds.top}}}return {left:viewport.scrollLeft,top:viewport.scrollTop,anchor}}
function restoreViewport(state){viewport.scrollLeft=state.left;viewport.scrollTop=state.top;if(!state.anchor)return;const node=lanes.querySelector(`[data-id="${CSS.escape(state.anchor.id)}"]`);if(!node)return;const bounds=viewport.getBoundingClientRect(),rect=node.getBoundingClientRect();viewport.scrollLeft+=rect.left-bounds.left-state.anchor.left;viewport.scrollTop+=rect.top-bounds.top-state.anchor.top}
function filterBotMergeRequests(result){if(showBots.checked)return result;const hidden=new Set(result.nodes.filter(node=>node.kind==='pullRequest'&&node.pullRequest.isBot).map(node=>node.id));if(!hidden.size)return result;const outgoing=new Map(),original=new Map();for(const edge of result.edges){if(!outgoing.has(edge.source))outgoing.set(edge.source,[]);outgoing.get(edge.source).push(edge.target);original.set(edge.source+'\0'+edge.target,edge)}const nodeByID=new Map(result.nodes.map(node=>[node.id,node])),reaches=start=>{const queue=[...(outgoing.get(start)||[])],seen=new Set();while(queue.length){const id=queue.shift();if(seen.has(id))continue;seen.add(id);const node=nodeByID.get(id);if(node?.kind==='pullRequest'&&!hidden.has(id))return true;queue.push(...(outgoing.get(id)||[]))}return false},visibleRepos=new Set(result.nodes.filter(node=>node.kind==='pullRequest'&&!hidden.has(node.id)).map(node=>node.pullRequest.repositoryId)),nodes=result.nodes.filter(node=>!hidden.has(node.id)&&(node.kind!=='repository'||visibleRepos.has(node.repository.id))&&(node.kind!=='branch'||reaches(node.id))),allowed=new Set(nodes.map(node=>node.id)),edgesOut=[],seen=new Set();for(const source of allowed){const queue=[...(outgoing.get(source)||[])],visited=new Set();while(queue.length){const target=queue.shift();if(visited.has(target))continue;visited.add(target);if(hidden.has(target)){queue.push(...(outgoing.get(target)||[]));continue}if(!allowed.has(target))continue;const key=source+'\0'+target;if(!seen.has(key)){seen.add(key);edgesOut.push(original.get(key)||{id:'filtered:'+edgesOut.length,source,target})}}}return {...result,nodes,edges:edgesOut}}
function render(result){if(!pendingViewportState)pendingViewportState=captureViewport();data=result;lanes.innerHTML='';graphOptions.hidden=false;const repos=result.nodes.filter(node=>node.kind==='repository'),byRepo=new Map();for(const node of result.nodes){if(node.kind==='repository')continue;const id=nodeRepositoryID(node);if(!byRepo.has(id))byRepo.set(id,[]);byRepo.get(id).push(node)}for(const repo of repos){const nodes=byRepo.get(repo.repository.id)||[],lane=document.createElement('section');lane.className='repo-lane';lane.innerHTML=nodeHTML(repo)+nodes.map(nodeHTML).join('');lanes.append(lane);layoutLane(lane,repo,nodes,result)}empty.hidden=result.nodes.length>0;warnings.textContent=(result.warnings||[]).join(' ');if(renderFrame!==null)cancelAnimationFrame(renderFrame);renderFrame=requestAnimationFrame(()=>{const state=pendingViewportState;pendingViewportState=null;renderFrame=null;if(state)restoreViewport(state);drawEdges()})}
function drawEdges(){if(!data)return;const canvas=document.querySelector('#canvas'),base=canvas.getBoundingClientRect();edges.innerHTML='';for(const edge of data.edges){const a=document.querySelector(`[data-id="${CSS.escape(edge.source)}"]`),b=document.querySelector(`[data-id="${CSS.escape(edge.target)}"]`);if(!a||!b)continue;const ar=a.getBoundingClientRect(),br=b.getBoundingClientRect(),x1=ar.right-base.left,y1=ar.top+ar.height/2-base.top,x2=br.left-base.left,y2=br.top+br.height/2-base.top,m=(x1+x2)/2,path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',Math.abs(y1-y2)<.5?`M${x1},${y1} L${x2},${y2}`:`M${x1},${y1} C${m},${y1} ${m},${y2} ${x2},${y2}`);path.setAttribute('fill','none');path.setAttribute('stroke','var(--line)');path.setAttribute('stroke-width','2');if(edge.dashed)path.setAttribute('stroke-dasharray','6 5');edges.append(path)}}
function setLoadProgress(percent,phase='Loading merge requests',collected){const reported=Math.max(0,Math.min(99,percent||0)),value=Math.max(3,loadProgressValue,reported);loadProgressValue=value;progress.setAttribute('aria-valuenow',String(value));progress.querySelector('.progress-bar').style.width=value+'%';if(phase!=='Complete')progress.querySelector('span').textContent=Number.isInteger(collected)&&collected>0?`${phase} · ${collected} MR${collected===1?'':'s'} collected`:phase}
async function completeLoadProgress(){loadProgressValue=100;progress.setAttribute('aria-valuenow','100');progress.querySelector('.progress-bar').style.width='100%';await new Promise(resolve=>setTimeout(resolve,120))}
async function readGraphResponse(response,onResult){if(!response.ok)throw new Error(response.statusText||'GitLab response failed');if(!response.headers.get('content-type')?.includes('application/x-ndjson'))return response.json();return graphStream.read(response.body.getReader(),event=>{if(event.type==='progress')setLoadProgress(event.percent,event.phase,event.collected);if(event.type==='result')onResult?.(event.result,event.stage)})}
function graphURL(){const query=new URLSearchParams({q:input.value,authored:scopeAuthored.checked?'1':'0',assigned:scopeAssigned.checked?'1':'0',reviewRequested:scopeReview.checked?'1':'0'});return '/api/v1/graph?'+query}
async function load(){if(loading)return;const showLog=!initialLoadComplete;loading=true;progress.hidden=false;progress.classList.toggle('quiet',!showLog);loadProgressValue=0;setLoadProgress(3);refresh.disabled=true;updated.textContent='Loading…';errorBox.hidden=true;try{await new Promise(resolve=>requestAnimationFrame(resolve));let streamed=false;const display=body=>{streamed=true;sourceData=body;render(filterBotMergeRequests(body))},body=await refreshTiming.withTimeout(signal=>fetch(graphURL(),{signal}).then(response=>readGraphResponse(response,display)));if(!streamed){sourceData=body;setLoadProgress(80,'Rendering merge request graph');render(filterBotMergeRequests(body))}initialLoadComplete=true;lastUpdated=Date.now();refreshFailures=0;retryAt=0;updated.textContent='Updated '+new Date(lastUpdated).toLocaleTimeString();await completeLoadProgress();progress.hidden=true}catch(error){refreshFailures++;retryAt=Date.now()+refreshTiming.retryDelay(refreshFailures);const timedOut=refreshTiming.isAbortError(error);errorBox.textContent=timedOut?refreshTiming.timeoutMessage():(error.message||'GitLab refresh failed');errorBox.hidden=false;updated.textContent=timedOut?'Refresh timed out':(lastUpdated?'Update failed':'Load failed')}finally{loading=false;progress.hidden=true;refresh.disabled=false;schedule()}}
function schedule(){clearTimeout(timer);if(!auto.checked||document.hidden||!navigator.onLine)return;const delay=refreshTiming.nextDelay(Date.now(),lastUpdated,refreshFailures,retryAt);timer=setTimeout(load,delay)}
function resumeAutoRefresh(){if(refreshFailures&&Date.now()<retryAt)schedule();else if(Date.now()-lastUpdated>=refreshTiming.refreshInterval)load();else schedule()}
function updateURL(){const query=new URLSearchParams();if(input.value.trim())query.set('q',input.value.trim());query.set('authored',scopeAuthored.checked?'1':'0');query.set('assigned',scopeAssigned.checked?'1':'0');query.set('reviewRequested',scopeReview.checked?'1':'0');history.replaceState(null,'','?'+query)}
form.addEventListener('submit',event=>{event.preventDefault();updateURL();lastUpdated=0;refreshFailures=0;retryAt=0;load()});showBots.addEventListener('change',()=>{if(sourceData)render(filterBotMergeRequests(sourceData))});refresh.addEventListener('click',load);auto.addEventListener('change',resumeAutoRefresh);document.addEventListener('visibilitychange',()=>{if(!document.hidden)resumeAutoRefresh()});window.addEventListener('online',resumeAutoRefresh);window.addEventListener('offline',schedule);window.addEventListener('resize',drawEdges);
let drag=null;viewport.addEventListener('pointerdown',e=>{if(e.target.closest('a,button,input'))return;drag={x:e.clientX,y:e.clientY,l:viewport.scrollLeft,t:viewport.scrollTop};viewport.classList.add('dragging');viewport.setPointerCapture(e.pointerId)});viewport.addEventListener('pointermove',e=>{if(drag){viewport.scrollLeft=drag.l-(e.clientX-drag.x);viewport.scrollTop=drag.t-(e.clientY-drag.y)}});viewport.addEventListener('pointerup',()=>{drag=null;viewport.classList.remove('dragging')});
refreshTiming.withTimeout(signal=>fetch('/api/v1/meta',{signal}).then(response=>response.ok?response.json():null)).then(meta=>{if(!meta?.version)return;brand.dataset.version=`Version ${meta.version}`;brand.setAttribute('aria-label',`MR Graph ${meta.version} on GitHub`)}).catch(()=>{});load();
